{% set name = "python-benedict" %}
{% set version = "0.23.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-benedict-{{ version }}.tar.gz
  sha256: 76bc84b0b2357af9f980fea7512aeb855942ecab0537afc071ec9140b912b6e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - ftfy
    - mailchecker
    - phonenumbers
    - python >=3.4
    - python-dateutil
    - python-slugify
    - pyyaml
    - requests
    - six
    - toml
    - xmltodict

test:
  imports:
    - benedict
    - benedict.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fabiocaccamo/python-benedict
  summary: python-benedict is a dict subclass with keylist/keypath support, I/O shortcuts (base64, csv, json, pickle, plist, query-string, toml, xml, yaml) and many utilities... for humans, obviously.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pmrowla
    - efiop
    - shcheklein
    - fabiocaccamo
